SELECT TOP (1000) [TypeID]
      ,[TSInsert]
      ,[TSUpdate]
      ,[RowVersion]
      ,[Name]
      ,[ObjectName]
      ,[Description]
      ,[EnglishName]
  FROM [BPS_Content].[dbo].[DicFieldDetailTypes]