SELECT TOP (1000) [FDEF_ID]
      ,[FDEF_WFFieldTypeID]
      ,[FDEF_TSInsert]
      ,[FDEF_TSUpdate]
      ,[FDEF_RowVersion]
      ,[FDEF_IsDeleted]
      ,[FDEF_Name]
      ,[FDEF_Description]
      ,[FDEF_Guid]
  FROM [BPS_Content].[dbo].[WFFieldDefinitions]