SELECT TOP (1000) [WFCON_ID]
      ,[WFCON_FDEFID]
      ,[WFCON_DEFID]
      ,[WFCON_FieldTypeID]
      ,[WFCON_IsArchival]
      ,[WFCON_IsTechnical]
      ,[WFCON_ChoiceFieldType]
      ,[WFCON_Prompt]
  FROM [BPS_Content].[dbo].[WFConfigurations]