SELECT TOP (1000) [WF_ID]
      ,[WF_WFDEFID]
      ,[WF_TSInsert]
      ,[WF_TSUpdate]
      ,[WF_RowVersion]
      ,[WF_IsDeleted]
      ,[WF_Version]
      ,[WF_AttachmentSecurityLevel]
      ,[WF_AllowToStartManually]
      ,[WF_SignatureDefinition]
      ,[WF_Name]
      ,[WF_Description]
      ,[WF_ProcedureFilePath]
      ,[WF_Guid]
      ,[WF_DocumentationDescription]
      ,[WF_Acronym]
      ,[WF_DesignerData]
  FROM [BPS_Content].[dbo].[WorkFlows]