//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebconWrapper.ConfigServices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfigServices {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigServices() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebconWrapper.ConfigServices.ConfigServices", typeof(ConfigServices).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    wf.WF_Name as WF_Name,
        ///    c.[WFCON_ID] as A_Id
        ///      , c.[WFCON_FDEFID]
        ///      , c.[WFCON_DEFID] as DEFID
        ///      , c.[WFCON_FieldTypeID] as A_TypeId
        ///    --   , c.[WFCON_IsArchival]
        ///    --   , c.[WFCON_IsTechnical]
        ///      , c.[WFCON_ChoiceFieldType]
        ///      , c.[WFCON_Prompt] as A_Title
        ///      , d.Name as A_Type
        ///      , d.ObjectName
        ///--   , d.EnglishName
        ///FROM [BPS_Content].[dbo].[WFConfigurations] c
        ///    INNER JOIN
        ///    (SELECT
        ///        [TypeID]
        ///      , [Name]
        ///      , [ObjectName]
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AllAttritubes {
            get {
                return ResourceManager.GetString("AllAttritubes", resourceCulture);
            }
        }
    }
}
